// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc1NzpK0Gnb9DDWIdsNMwhc9TEqlf3nHk',
    appId: '1:883428603523:web:0fe1ce6bd5f45e6fe00db6',
    messagingSenderId: '883428603523',
    projectId: 'flutterdemoapp2',
    authDomain: 'flutterdemoapp2.firebaseapp.com',
    storageBucket: 'flutterdemoapp2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFfJT-tvlUd5Nbmmn37CXVQIJDgL9qKos',
    appId: '1:883428603523:android:eab146ff43a653bce00db6',
    messagingSenderId: '883428603523',
    projectId: 'flutterdemoapp2',
    storageBucket: 'flutterdemoapp2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrV9IDNWv2LKG9i6wh6OgFVYrtf_eiIMY',
    appId: '1:883428603523:ios:cc736e04157a1e31e00db6',
    messagingSenderId: '883428603523',
    projectId: 'flutterdemoapp2',
    storageBucket: 'flutterdemoapp2.appspot.com',
    iosClientId: '883428603523-m2pqd7u2jeibsrfh9os8eoem00qffm16.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemoApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrV9IDNWv2LKG9i6wh6OgFVYrtf_eiIMY',
    appId: '1:883428603523:ios:cc736e04157a1e31e00db6',
    messagingSenderId: '883428603523',
    projectId: 'flutterdemoapp2',
    storageBucket: 'flutterdemoapp2.appspot.com',
    iosClientId: '883428603523-m2pqd7u2jeibsrfh9os8eoem00qffm16.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemoApp2',
  );
}
